enum LocalizationKeys {
  signUpForTiktok('auth.signUpForTiktok'),
  authTopText('auth.authTopText'),
  signUpAppBarTitle('auth.signUpAppBarTitle'),
  signUpFacebookButtonText('auth.signUpFacebookButtonText'),
  signUpEmailOrPhoneButtonText('auth.signUpEmailOrPhoneButtonText'),
  signUpAppleButtonText('auth.signUpAppleButtonText'),
  signUpGoogleButtonText('auth.signUpGoogleButtonText'),
  signUpXButtonText('auth.signUpXButtonText'),
  signUpTermOfServiceText('auth.signUpTermOfServiceText'),
  signUpTermOfServiceText2('auth.signUpTermOfServiceText2'),
  signUpPhoneTabText('auth.signUpPhoneTabText'),
  signUpEmailTabText('auth.signUpEmailTabText'),
  signUpAlreadyHaveAnAccount('auth.signUpAlreadyHaveAnAccount'),
  signUpPhoneNumberHintText('auth.signUpPhoneNumberHintText'),
  signUpPhoneFieldBottomText('auth.signUpPhoneFieldBottomText'),
  signUpPhoneFieldSendCode('auth.signUpPhoneFieldSendCode'),
  signUpEmailHintText('auth.signUpEmailHintText'),
  signUpEmailNotificationText('auth.signUpEmailNotificationText'),
  signUpCaptchaDialogTitle('auth.signUpCaptchaDialogTitle'),
  signUpCaptchaDialogSliderText('auth.signUpCaptchaDialogSliderText'),
  signUpCreatePassword('auth.signUpCreatePassword'),
  signUpCreatePasswordHintText('auth.signUpCreatePasswordHintText'),
  signUpCreatePasswordHaveMustText('auth.signUpCreatePasswordHaveMustText'),
  signUpCreatePasswordValidatingText1('auth.signUpCreatePasswordValidatingText1'),
  signUpCreatePasswordValidatingText2('auth.signUpCreatePasswordValidatingText2'),
  signUpCreatePasswordValidatingText3('auth.signUpCreatePasswordValidatingText3'),
  signUpBirthdayTitle('auth.signUpBirthdayTitle'),
  signUpBirthdayWontBeShownPublicly('auth.signUpBirthdayWontBeShownPublicly'),
  signUpBirthdayHintText('auth.signUpBirthdayHintText'),
  errorPhoneFieldEmpty('error.phoneFieldEmpty'),
  errorPhoneFieldInvalid('error.phoneFieldInvalid'),
  errorEmailFieldEmpty('error.emailFieldEmpty'),
  errorEmailFieldInvalid('error.emailFieldInvalid'),
  nextButtonText('nextButtonText');

  const LocalizationKeys(this.name);

  final String name;
}
